# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(728, 642)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 700, 500))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 251, 21))
        self.label.setStyleSheet("color: rgb(0, 0, 0);\n"
                                 "font: 16pt \"MS UI Gothic\";\n"
                                 "background-color: rgb(170, 158, 146);")
        self.label.setObjectName("label")
        self.addEditCoffeeForm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addEditCoffeeForm.setGeometry(QtCore.QRect(40, 540, 291, 41))
        self.addEditCoffeeForm.setStyleSheet("color: rgb(0, 0, 0);\n"
                                             "font: 10pt \"MS UI Gothic\";\n"
                                             "background-color: rgb(170, 158, 146);")
        self.addEditCoffeeForm.setObjectName("addEditCoffeeForm")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Coffe"))
        self.addEditCoffeeForm.setText(_translate("MainWindow", "Удалить/Изменить данные"))
